---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: pets
  labels:
    app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata: ~

    output.kafka:
      hosts: ["kafka:9092"]
      topic: 'metricbeat'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "metricbeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: pets
  labels:
    app: metricbeat
data:
  # This module requires `kube-state-metrics` up and running under `kube-system` namespace
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["kube-state-metrics.kube-system.svc.cluster.local:8080"]
      add_metadata: true
      in_cluster: true
    - module: kubernetes
      enabled: true
      metricsets:
        - apiserver
      hosts: ["https://kubernetes.default:443"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: pets
  labels:
    app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    # To enable hints based autodiscover uncomment this:
    metricbeat.autodiscover:
     providers:
       - type: kubernetes
         host: ${NODE_NAME}
         hints.enabled: true

    processors:
      - add_cloud_metadata: ~
      - add_host_metadata:
          netinfo.enabled: false

    output.kafka:
      hosts: ["kafka:9092"]
      topic: 'metricbeat'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "metricbeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  namespace: pets
  labels:
    app: metricbeat
data:
  system.yml: |-
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - core
        - diskio
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory

    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: ${NODE_NAME}
      hosts: ["localhost:10255"]
  docker.yml: |-
    - module: docker
      metricsets:
        - "container"
        - "cpu"
        - "diskio"
        - "healthcheck"
        - "info"
        - "image"
        - "memory"
        - "network"
      hosts: ["unix:///var/run/docker.sock"]
      period: 10s
      enabled: true
  elastic.yml: |-
    - module: elasticsearch
      metricsets:
        - node
        - node_stats
        - index
        - index_recovery
        - index_summary
        - shard
        - ml_job
      period: 10s
      hosts: ["elasticsearch:9200"]
    - module: logstash
      metricsets: ["node", "node_stats"]
      enabled: true
      period: 10s
      hosts: ["logstash:9600"]
    - module: kibana
      metricsets: ["status"]
      period: 10s
      hosts: ["kibana:5601"]
      basepath: ""
      enabled: true
  kafka.yml: |-
    - module: kafka
      metricsets: ["consumergroup", "partition"]
      period: 10s
      hosts: ["kafka:9092"]
      enabled: true
    - module: zookeeper
      enabled: true
      metricsets: ["mntr"]
      period: 10s
      hosts: ["zookeeper:2181"]