apiVersion: v1
kind: Service
metadata:
  name: todo-server
  namespace: elastic
  labels:
    app: todo-server
spec:
  type: LoadBalancer
  selector:
    app: todo-server
  ports:
    - name: http
      port: 8081
      protocol: TCP