apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: apm-server
  namespace: pets
  labels:
    app: apm-server
spec:
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: appropriate/curl
          imagePullPolicy: IfNotPresent
          args:
          - "sh"
          - "-c"
          - "while [ $(curl -sw '%{http_code}' 'http://elasticsearch.pets.svc.cluster.local:9200/_cluster/health?pretty' -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:6.6.1
        ports:
        - containerPort: 8200
          name: apm-port
        volumeMounts:
        - name: apm-server-config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
      volumes:
      - name: apm-server-config
        configMap:
          name: apm-server-config
