---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: heartbeat
  namespace: pets
  labels:
    app: heartbeat
spec:
  template:
    metadata:
      labels:
        app: heartbeat
    spec:
      serviceAccountName: heartbeat
      terminationGracePeriodSeconds: 60
      containers:
      - name: heartbeat
        image: docker.elastic.co/beats/heartbeat:6.5.4
        args: [
          "-e"
        ]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/heartbeat/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
        - name: data
          mountPath: /usr/share/heartbeat/data
      volumes:
      - name: config
        configMap:
          name: heartbeat-config
          defaultMode: 0600
      - name: data
        hostPath:
          path: /var/lib/heartbeat
          type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  namespace: pets
  labels:
    app: heartbeat
data:
  heartbeat.yml: |-
    heartbeat.monitors:
    - type: http
      schedule: '@every 5s'
      urls:
        - http://elasticsearch:9200/_cluster/health
        - http://kibana:5601/status
        - http://logstash:9600/?pretty

    - type: icmp
      schedule: '@every 5s'
      hosts:
        - elasticsearch
        - kibana

    processors:
    - add_cloud_metadata:

    output.elasticsearch:
      hosts: ['http://elasticsearch:9200']

    setup.kibana:
      host: "http://kibana:5601"

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "heartbeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    xpack.monitoring.enabled: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
  labels:
    app: heartbeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heartbeat
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: pets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heartbeat
  labels:
    app: heartbeat
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat
  namespace: pets
  labels:
    app: heartbeat