---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    componet: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: discovery.type
            value: single-node
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        name: elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    componet: elasticsearch
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: http2
  selector:
    component: elasticsearch