apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    componet: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - env:
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: discovery.type
            value: single-node
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        name: elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data