apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    componet: elasticsearch
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}