kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: premium-expansion-enabled
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
allowVolumeExpansion: true