apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elastic
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - port: 5555
      protocol: TCP
      targetPort: beats