apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: elastic
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
  selector:
    app: kafka