---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-config
  namespace: pets
  labels:
    app: auditbeat
data:
  auditbeat.yml: |-
    auditbeat.config.modules:
      # Mounted `auditbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata:

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]

    output.kafka:
      hosts: ["kafka:9092"]
      topic: 'auditbeat'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "auditbeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-daemonset-modules
  namespace: pets
  labels:
    app: auditbeat
data:
  system.yml: |-
    - module: file_integrity
      paths:
      - /hostfs/bin
      - /hostfs/usr/bin
      - /hostfs/sbin
      - /hostfs/usr/sbin
      - /hostfs/etc
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin
      - /etc

    - module: system
      datasets:
        - host
        - process
        - socket
        - user
      period: 10s
      state.period: 12h
      user.detect_password_changes: true

    - module: auditd
      audit_rules: |
        -w /etc/passwd -p wa -k identity
        -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access