---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-config
  namespace: pets
  labels:
    app: auditbeat
data:
  auditbeat.yml: |-
    auditbeat.modules:
      - module: file_integrity
        paths:
          - /bin
          - /usr/bin
          - /sbin
          - /usr/sbin
          - /etc
    auditbeat.config.modules:
      # Mounted `auditbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata:

    xpack.monitoring.enabled: true

    output.elasticsearch:
      hosts: ['http://elasticsearch:9200']

    setup.kibana:
          host: "kibana:5601"

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "auditbeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-daemonset-modules
  namespace: pets
  labels:
    app: auditbeat
data:
  system.yml: |-
    - module: file_integrity
      paths:
      - /hostfs/bin
      - /hostfs/usr/bin
      - /hostfs/sbin
      - /hostfs/usr/sbin
      - /hostfs/etc
      exclude_files:
      - '(?i)\.sw[nop]$'
      - '~$'
      - '/\.git($|/)'
      scan_at_start: true
      scan_rate_per_sec: 50 MiB
      max_file_size: 100 MiB
      hash_types: [sha1]
      recursive: true