---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  labels:
    componet: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: todo-server
  template:
    metadata:
      labels:
        component: todo-server
    spec:
      containers:
        - name: todo-server
          image: atsistemas/todo-repo
          env:
            - name: ELASTIC_APM_SERVICE_NAME
              value: todo-server
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server:8200
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: com.atsistemas
            - name: ELASTIC_APM_ENABLE_LOG_CORRELATION
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx512M -Xms512M"
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: todo-server
  labels:
    component: todo-server
spec:
  type: LoadBalancer
  selector:
    component: todo-server
  ports:
    - name: http
      port: 8081
      protocol: TCP