apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  namespace: elastic
  labels:
    app: apm-server
data:
  apm-server.yml: |-

    apm-server:
      host: "0.0.0.0:8200"

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        # index: "apm-server-*"
      template:
        enabled: false
    
    xpack.monitoring:
      enabled: false
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]

    output.kafka:
      hosts: ["kafka-0.kafka-headless.elastic:9092"]
      topics:
      - topic: 'apm-%{[processor.event]}'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000