apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: apm-server
  namespace: elastic
  labels:
    app: apm-server
spec:
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: appropriate/curl
          resources:
            limits:
              cpu: 150m
              memory: 50Mi
            requests:
              cpu: 150m
              memory: 50Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - "sh"
          - "-c"
          - "while [ $(curl -sw %{http_code} http://kibana.${NAMESPACE}.svc.cluster.local:5601/api/status -o /dev/null) -ne 200 ]; do sleep 15; done"
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:6.7.1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8200
          name: apm-port
        volumeMounts:
        - name: apm-server-config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
      volumes:
      - name: apm-server-config
        configMap:
          name: apm-server-config
