apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic
  labels:
    app: kibana-config
data:
  kibana.yml: |-
    server:
      name: kibana
      host: "0"
    elasticsearch:
      hosts: http://elasticsearch:9200