---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elastic
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        # Mounted `filebeat-inputs` configmap:
        path: ${path.config}/inputs.d/*.yml
        # Reload inputs configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "filebeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    output.kafka:
      hosts: ["kafka:9092"]
      topic: 'filebeat'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  namespace: elastic
  labels:
    app: filebeat
data:
  inputs.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
      - add_kubernetes_metadata:
          in_cluster: true