---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: pets
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        # Mounted `filebeat-inputs` configmap:
        path: ${path.config}/inputs.d/*.yml
        # Reload inputs configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    processors:
      - add_cloud_metadata: ~

    setup.kibana:
      host: "kibana:5601"

    setup:
      kibana:
        host: "http://kibana:5601"
      dashboards:
        enabled: true
        index: "filebeat-*"
        retry:
          enabled: true
          interval: 30
      template:
        enabled: true

    output.logstash:
      hosts: ["logstash:5555"]

    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  namespace: pets
  labels:
    app: filebeat
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
      - add_kubernetes_metadata:
          in_cluster: true