apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: elastic
  labels:
    app: kafka
spec:
  ports:
    - port: 2181
      name: zookeeper-port
      targetPort: 2181
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: elastic
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka