apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client
  namespace: elastic
  labels:
    componet: todo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      component: todo-client
  template:
    metadata:
      labels:
        component: todo-client
    spec:
      containers:
        - name: todo-client
          image: atsistemas/todo-client
          env:
            - name: TODO_SERVER_URL
              value: http://todo-server:8081
            - name: ELASTIC_APM_SERVICE_NAME
              value: todo-client
            - name: ELASTIC_APM_SERVER_URLS
              value: http://apm-server:8200
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: com.atsistemas
            - name: ELASTIC_APM_ENABLE_LOG_CORRELATION
              value: "true"
            - name: JAVA_OPTS
              value: "-Xmx512M -Xms512M"
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP