apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: packetbeat
  namespace: pets
  labels:
    app: packetbeat
spec:
  template:
    metadata:
      labels:
        app: packetbeat
    spec:
      securityContext:
        runAsUser: 0
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: packetbeat
      containers:
      - name: packetbeat
        image: docker.elastic.co/beats/packetbeat:6.6.0
        imagePullPolicy: Always
        args: [
          "-e"
        ]
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.$(NAMESPACE).svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: KIBANA_HOST
          value: "kibana.$(NAMESPACE).svc.cluster.local"
        - name: KIBANA_PORT
          value: "5601"
        volumeMounts:
        - name: config
          mountPath: /usr/share/packetbeat/packetbeat.yml
          readOnly: true
          subPath: packetbeat.yml
        - name: data
          mountPath: /usr/share/packetbeat/data
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: packetbeat-config
      - name: data
        emptyDir: {}